# Generated by Django 4.1.4 on 2022-12-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('Correo', models.EmailField(blank=True, max_length=200, verbose_name='Correo')),
                ('Telefono', models.CharField(blank=True, max_length=200, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Direccion', models.CharField(blank=True, max_length=200, verbose_name='Direccion')),
                ('Telefono', models.CharField(blank=True, max_length=200, verbose_name='Telefono')),
                ('Correo', models.EmailField(blank=True, max_length=200, verbose_name='Correo')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactoAbajo',
        ),
        migrations.DeleteModel(
            name='ContactoArriba',
        ),
    ]
