# Generated by Django 4.1.4 on 2022-12-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0002_contacto_informacionpersonal_delete_contactoabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='Descripcion',
            field=models.TextField(null=True),
        ),
    ]
