# Generated by Django 4.1.4 on 2022-12-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0003_contacto_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='Correo',
            new_name='Correo1',
        ),
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='Telefono',
            new_name='Telefono1',
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='Correo2',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='Telefono2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Telefono2'),
        ),
    ]
