# Generated by Django 4.1.4 on 2022-12-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0004_rename_correo_informacionpersonal_correo1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(upload_to='sobreNosotros')),
                ('Titulo', models.CharField(blank=True, max_length=200)),
                ('Descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='Correo1',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Correo1'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='Correo2',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Correo2'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='Telefono1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Telefono1'),
        ),
    ]
